export const FETCH_ALBUM_REQUEST = "FETCH_ALBUM_REQUEST";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_FAILURE = "FETCH_ALBUM_FAILURE";

export const FETCH_ALBUM_BY_ID_REQUEST = "FETCH_ALBUM_BY_ID_REQUEST";
export const FETCH_ALBUM_BY_ID_SUCCESS = "FETCH_ALBUM_BY_ID_SUCCESS";
export const FETCH_ALBUM_BY_ID_FAILURE = "FETCH_ALBUM_BY_ID_FAILURE";